### ISSUE TITLE
Crash on V013

### ISSUE THREAD

**Issue by JeffersonAlmeida** [axiros/AXACT.AndroidSample#3]
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void com.axiros.axact.AXACTJNI.cwmpclientInit() (tried Java_com_axiros_axact_AXACTJNI_cwmpclientInit and Java_com_axiros_axact_AXACTJNI_cwmpclientInit__)
       at com.axiros.axact.AXACTJNI.cwmpclientInit(AXACTJNI.java)
       at com.axiros.axact.AXACT.cwmpclientInit(AXACT.java:13)
       at com.axiros.axact.AxirosService.onCreate(AxirosService.java:526)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2825)
       at android.app.ActivityThread.access$1800(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by cderivan** [comment]
Oi Jefferson, voce poderia me informar o MD5 da lib que voce esta usando ? 

Att

**Comment by cderivan** [comment]
erro referente ao download invalid, por favor refazer o download da library.
