### ISSUE TITLE
Crash no momento de capturar IMEI nos slots no dispositivo

### ISSUE THREAD

**Issue by JeffersonAlmeida** [axiros/AXACT.AndroidSample#4]
### Crash no momento de capturar IMEI nos slots no dispositivo.

* Crash on AxirosService simCount
* Analisar o método simCount abaixo
* O crash de NullPointerException acontece dentro do método simCount, porém foi desencadiado pelo método getFromTelephonyManagerBySlot.
* O método getFromTelephonyManagerBySlot deve ser investigado para validar corretamente
se o Device possui IMEI.

1 - Esse crash pode acontecer com dispositivos que não contenham slot, como 
por exemplo um tablet.

2 - Pode eventualmente acontecer para celulares de fabricantes específicos
mesmo que tenha slots com chips. 

```java
private int simCount() {
        String imeiSIM1 = this.getFromTelephonyManagerBySlot(this, "getDeviceId", 0);
        String imeiSIM2 = this.getFromTelephonyManagerBySlot(this, "getDeviceId", 1);
        return imeiSIM1.equals(imeiSIM2)?1:2;
    }
```

```java
 private String getFromTelephonyManagerBySlot(Context context, String predictedMethodName, int slotID) {
        String data = null;
        TelephonyManager telephony = (TelephonyManager)context.getSystemService("phone");

        try {
            Class e = Class.forName(telephony.getClass().getName());
            Class[] parameter = new Class[]{Integer.TYPE};
            Method getSimID = e.getMethod(predictedMethodName, parameter);
            Object[] obParameter = new Object[]{Integer.valueOf(slotID)};
            Object ob_phone = getSimID.invoke(telephony, obParameter);
            if(ob_phone != null) {
                data = ob_phone.toString();
            }
        } catch (Exception var11) {
            var11.printStackTrace();
        }

        return data;
    }
```

```java
Fatal Exception: java.lang.RuntimeException: Unable to create service com.axiros.axact.AxirosService: java.lang.NullPointerException
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2749)
       at android.app.ActivityThread.access$1800(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.axiros.axact.AxirosService.simCount(AxirosService.java:688)
       at com.axiros.axact.AxirosService.onCreate(AxirosService.java:740)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2739)
       at android.app.ActivityThread.access$1800(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by AxTNogueira** [comment]
[Axactlib_v016_DeviceFarmValidation.zip](https://github.com/axiros/AXACT.AndroidSample/files/1518839/Axactlib_v016_DeviceFarmValidation.zip)
Olá Jefferson,

Esse ISSUE foi fixado na versão-016 da lib que já encontra-se disponível para download:
https://github.com/axiros/AXACT.AndroidSample/releases

Foram realizados testes de validação bem sucedidos via Device Farm em diferentes dispositivos (incluindo Tablets) e diferentes versões de Android. Os Log's e evidências estão anexados nesse reporte.

Agradecemos o feedback, é sempre bem-vindo.
Qualquer dúvida ou auxilio seguimos a disposição.  

Axiros Team.
