### ISSUE TITLE
Null object reference

### ISSUE THREAD

**Issue by brunordg** [axiros/AXACT.AndroidSample#6]
Estou recebendo a seguinte exception na integração, poderiam verificar?

```
Fatal Exception: java.lang.RuntimeException: Unable to stop service com.axiros.axact.AxirosService@1ceba83: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.axiros.axact.AXACTEventsListener.clear()' on a null object reference
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3608)
       at android.app.ActivityThread.-wrap26(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1716)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.axiros.axact.AXACTEventsListener.clear()' on a null object reference
       at com.axiros.axact.AxirosService.onDestroy(AxirosService.java:780)
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3590)
       at android.app.ActivityThread.-wrap26(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1716)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

**Comment by rsfreitas** [comment]
@brunordg fizemos algumas melhorias no controle do serviço na última release disponibilizada, veja se ela lhe atende Ok?
