### ISSUE TITLE
NullPointerException na hora de parar o serviço

### ISSUE THREAD

**Issue by RafaelSermenho** [axiros/AXACT.AndroidSample#8]
Pessoal, nos últimos dias estamos recebendo muitos erros com essa stack (estamos usando a versão axactandroid-release-all-v.3.2.6-019:

`Fatal Exception: java.lang.RuntimeException: Unable to stop service com.axiros.axact.AxirosService@e393ad5: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.axiros.axact.AXACTEventsListener.clear()' on a null object reference
       at android.app.ActivityThread.handleStopService(ActivityThread.java:3741)
       at android.app.ActivityThread.-wrap28(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1832)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

**Comment by rsfreitas** [comment]
@RafaelSermenho corrigimos este erro na última release v020. Se possível,
faça a atualização para ela. Ok?
